// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: handtracking.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Represents a 4x4 transformation matrix for a joint
public struct Handtracking_Matrix4x4: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var m00: Float = 0

  public var m01: Float = 0

  public var m02: Float = 0

  public var m03: Float = 0

  public var m10: Float = 0

  public var m11: Float = 0

  public var m12: Float = 0

  public var m13: Float = 0

  public var m20: Float = 0

  public var m21: Float = 0

  public var m22: Float = 0

  public var m23: Float = 0

  public var m30: Float = 0

  public var m31: Float = 0

  public var m32: Float = 0

  public var m33: Float = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// The skeleton of a hand, comprising multiple 4x4 matrices (one per joint)
public struct Handtracking_Skeleton: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Array of 4x4 matrices, expecting 24 per hand based on your structure
  public var jointMatrices: [Handtracking_Matrix4x4] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// The hand tracking information, including the full 4x4 matrix for the wrist and the skeleton
public struct Handtracking_Hand: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 4x4 matrix for the wrist position and orientation
  public var wristMatrix: Handtracking_Matrix4x4 {
    get {return _storage._wristMatrix ?? Handtracking_Matrix4x4()}
    set {_uniqueStorage()._wristMatrix = newValue}
  }
  /// Returns true if `wristMatrix` has been explicitly set.
  public var hasWristMatrix: Bool {return _storage._wristMatrix != nil}
  /// Clears the value of `wristMatrix`. Subsequent reads from it will return its default value.
  public mutating func clearWristMatrix() {_uniqueStorage()._wristMatrix = nil}

  /// The hand's skeleton
  public var skeleton: Handtracking_Skeleton {
    get {return _storage._skeleton ?? Handtracking_Skeleton()}
    set {_uniqueStorage()._skeleton = newValue}
  }
  /// Returns true if `skeleton` has been explicitly set.
  public var hasSkeleton: Bool {return _storage._skeleton != nil}
  /// Clears the value of `skeleton`. Subsequent reads from it will return its default value.
  public mutating func clearSkeleton() {_uniqueStorage()._skeleton = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// The overall hand update message, including data for both hands
public struct Handtracking_HandUpdate: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var leftHand: Handtracking_Hand {
    get {return _storage._leftHand ?? Handtracking_Hand()}
    set {_uniqueStorage()._leftHand = newValue}
  }
  /// Returns true if `leftHand` has been explicitly set.
  public var hasLeftHand: Bool {return _storage._leftHand != nil}
  /// Clears the value of `leftHand`. Subsequent reads from it will return its default value.
  public mutating func clearLeftHand() {_uniqueStorage()._leftHand = nil}

  public var rightHand: Handtracking_Hand {
    get {return _storage._rightHand ?? Handtracking_Hand()}
    set {_uniqueStorage()._rightHand = newValue}
  }
  /// Returns true if `rightHand` has been explicitly set.
  public var hasRightHand: Bool {return _storage._rightHand != nil}
  /// Clears the value of `rightHand`. Subsequent reads from it will return its default value.
  public mutating func clearRightHand() {_uniqueStorage()._rightHand = nil}

  public var head: Handtracking_Matrix4x4 {
    get {return _storage._head ?? Handtracking_Matrix4x4()}
    set {_uniqueStorage()._head = newValue}
  }
  /// Returns true if `head` has been explicitly set.
  public var hasHead: Bool {return _storage._head != nil}
  /// Clears the value of `head`. Subsequent reads from it will return its default value.
  public mutating func clearHead() {_uniqueStorage()._head = nil}

  /// R1 tracking protocol v1: source times use the Vision Pro monotonic clock.
  /// sample_time is serialization time; *_time are ARKit anchor timestamps.
  /// A valid hand requires a tracked anchor and all of its first 25 joints.
  public var trackingProtocolVersion: UInt32 {
    get {return _storage._trackingProtocolVersion}
    set {_uniqueStorage()._trackingProtocolVersion = newValue}
  }

  public var sampleTime: Double {
    get {return _storage._sampleTime}
    set {_uniqueStorage()._sampleTime = newValue}
  }

  public var headTime: Double {
    get {return _storage._headTime}
    set {_uniqueStorage()._headTime = newValue}
  }

  public var leftTime: Double {
    get {return _storage._leftTime}
    set {_uniqueStorage()._leftTime = newValue}
  }

  public var rightTime: Double {
    get {return _storage._rightTime}
    set {_uniqueStorage()._rightTime = newValue}
  }

  public var headValid: Bool {
    get {return _storage._headValid}
    set {_uniqueStorage()._headValid = newValue}
  }

  public var leftValid: Bool {
    get {return _storage._leftValid}
    set {_uniqueStorage()._leftValid = newValue}
  }

  public var rightValid: Bool {
    get {return _storage._rightValid}
    set {_uniqueStorage()._rightValid = newValue}
  }

  public var predictionSeconds: Double {
    get {return _storage._predictionSeconds}
    set {_uniqueStorage()._predictionSeconds = newValue}
  }

  /// Diagnostics capability v1; additive to tracking protocol v1.
  /// Loss counters persist for the app lifetime and count valid-to-invalid edges,
  /// including edges hidden by sender/receiver coalescing. head_loss_seq includes
  /// both raw head tracking loss and the first-person video gate.
  public var diagnosticsVersion: UInt32 {
    get {return _storage._diagnosticsVersion}
    set {_uniqueStorage()._diagnosticsVersion = newValue}
  }

  public var headAnchorValid: Bool {
    get {return _storage._headAnchorValid}
    set {_uniqueStorage()._headAnchorValid = newValue}
  }

  public var videoRequired: Bool {
    get {return _storage._videoRequired}
    set {_uniqueStorage()._videoRequired = newValue}
  }

  public var videoReady: Bool {
    get {return _storage._videoReady}
    set {_uniqueStorage()._videoReady = newValue}
  }

  public var videoReason: String {
    get {return _storage._videoReason}
    set {_uniqueStorage()._videoReason = newValue}
  }

  public var headLossSeq: UInt64 {
    get {return _storage._headLossSeq}
    set {_uniqueStorage()._headLossSeq = newValue}
  }

  public var leftLossSeq: UInt64 {
    get {return _storage._leftLossSeq}
    set {_uniqueStorage()._leftLossSeq = newValue}
  }

  public var rightLossSeq: UInt64 {
    get {return _storage._rightLossSeq}
    set {_uniqueStorage()._rightLossSeq = newValue}
  }

  /// Previous local RPC write duration; not a network RTT or delivery ack.
  public var lastWriteMs: Double {
    get {return _storage._lastWriteMs}
    set {_uniqueStorage()._lastWriteMs = newValue}
  }

  /// Ordinal of this pose packet within the current RPC, starting at one.
  public var packetsSent: UInt64 {
    get {return _storage._packetsSent}
    set {_uniqueStorage()._packetsSent = newValue}
  }

  /// Cause of the most recent head_loss_seq edge, retained after recovery.
  public var headLossReason: String {
    get {return _storage._headLossReason}
    set {_uniqueStorage()._headLossReason = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Acknowledgement message for hand updates
public struct Handtracking_HandUpdateAck: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var message: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "handtracking"

extension Handtracking_Matrix4x4: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Matrix4x4"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}m00\0\u{1}m01\0\u{1}m02\0\u{1}m03\0\u{1}m10\0\u{1}m11\0\u{1}m12\0\u{1}m13\0\u{1}m20\0\u{1}m21\0\u{1}m22\0\u{1}m23\0\u{1}m30\0\u{1}m31\0\u{1}m32\0\u{1}m33\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.m00) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.m01) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.m02) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.m03) }()
      case 5: try { try decoder.decodeSingularFloatField(value: &self.m10) }()
      case 6: try { try decoder.decodeSingularFloatField(value: &self.m11) }()
      case 7: try { try decoder.decodeSingularFloatField(value: &self.m12) }()
      case 8: try { try decoder.decodeSingularFloatField(value: &self.m13) }()
      case 9: try { try decoder.decodeSingularFloatField(value: &self.m20) }()
      case 10: try { try decoder.decodeSingularFloatField(value: &self.m21) }()
      case 11: try { try decoder.decodeSingularFloatField(value: &self.m22) }()
      case 12: try { try decoder.decodeSingularFloatField(value: &self.m23) }()
      case 13: try { try decoder.decodeSingularFloatField(value: &self.m30) }()
      case 14: try { try decoder.decodeSingularFloatField(value: &self.m31) }()
      case 15: try { try decoder.decodeSingularFloatField(value: &self.m32) }()
      case 16: try { try decoder.decodeSingularFloatField(value: &self.m33) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.m00.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m00, fieldNumber: 1)
    }
    if self.m01.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m01, fieldNumber: 2)
    }
    if self.m02.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m02, fieldNumber: 3)
    }
    if self.m03.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m03, fieldNumber: 4)
    }
    if self.m10.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m10, fieldNumber: 5)
    }
    if self.m11.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m11, fieldNumber: 6)
    }
    if self.m12.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m12, fieldNumber: 7)
    }
    if self.m13.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m13, fieldNumber: 8)
    }
    if self.m20.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m20, fieldNumber: 9)
    }
    if self.m21.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m21, fieldNumber: 10)
    }
    if self.m22.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m22, fieldNumber: 11)
    }
    if self.m23.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m23, fieldNumber: 12)
    }
    if self.m30.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m30, fieldNumber: 13)
    }
    if self.m31.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m31, fieldNumber: 14)
    }
    if self.m32.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m32, fieldNumber: 15)
    }
    if self.m33.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.m33, fieldNumber: 16)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_Matrix4x4, rhs: Handtracking_Matrix4x4) -> Bool {
    if lhs.m00 != rhs.m00 {return false}
    if lhs.m01 != rhs.m01 {return false}
    if lhs.m02 != rhs.m02 {return false}
    if lhs.m03 != rhs.m03 {return false}
    if lhs.m10 != rhs.m10 {return false}
    if lhs.m11 != rhs.m11 {return false}
    if lhs.m12 != rhs.m12 {return false}
    if lhs.m13 != rhs.m13 {return false}
    if lhs.m20 != rhs.m20 {return false}
    if lhs.m21 != rhs.m21 {return false}
    if lhs.m22 != rhs.m22 {return false}
    if lhs.m23 != rhs.m23 {return false}
    if lhs.m30 != rhs.m30 {return false}
    if lhs.m31 != rhs.m31 {return false}
    if lhs.m32 != rhs.m32 {return false}
    if lhs.m33 != rhs.m33 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_Skeleton: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Skeleton"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}jointMatrices\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.jointMatrices) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.jointMatrices.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.jointMatrices, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_Skeleton, rhs: Handtracking_Skeleton) -> Bool {
    if lhs.jointMatrices != rhs.jointMatrices {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_Hand: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Hand"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}wristMatrix\0\u{1}skeleton\0")

  fileprivate class _StorageClass {
    var _wristMatrix: Handtracking_Matrix4x4? = nil
    var _skeleton: Handtracking_Skeleton? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _wristMatrix = source._wristMatrix
      _skeleton = source._skeleton
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._wristMatrix) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._skeleton) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._wristMatrix {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._skeleton {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_Hand, rhs: Handtracking_Hand) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._wristMatrix != rhs_storage._wristMatrix {return false}
        if _storage._skeleton != rhs_storage._skeleton {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_HandUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HandUpdate"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}left_hand\0\u{3}right_hand\0\u{1}Head\0\u{3}tracking_protocol_version\0\u{3}sample_time\0\u{3}head_time\0\u{3}left_time\0\u{3}right_time\0\u{3}head_valid\0\u{3}left_valid\0\u{3}right_valid\0\u{3}prediction_seconds\0\u{3}diagnostics_version\0\u{3}head_anchor_valid\0\u{3}video_required\0\u{3}video_ready\0\u{3}video_reason\0\u{3}head_loss_seq\0\u{3}left_loss_seq\0\u{3}right_loss_seq\0\u{3}last_write_ms\0\u{3}packets_sent\0\u{3}head_loss_reason\0")

  fileprivate class _StorageClass {
    var _leftHand: Handtracking_Hand? = nil
    var _rightHand: Handtracking_Hand? = nil
    var _head: Handtracking_Matrix4x4? = nil
    var _trackingProtocolVersion: UInt32 = 0
    var _sampleTime: Double = 0
    var _headTime: Double = 0
    var _leftTime: Double = 0
    var _rightTime: Double = 0
    var _headValid: Bool = false
    var _leftValid: Bool = false
    var _rightValid: Bool = false
    var _predictionSeconds: Double = 0
    var _diagnosticsVersion: UInt32 = 0
    var _headAnchorValid: Bool = false
    var _videoRequired: Bool = false
    var _videoReady: Bool = false
    var _videoReason: String = String()
    var _headLossSeq: UInt64 = 0
    var _leftLossSeq: UInt64 = 0
    var _rightLossSeq: UInt64 = 0
    var _lastWriteMs: Double = 0
    var _packetsSent: UInt64 = 0
    var _headLossReason: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _leftHand = source._leftHand
      _rightHand = source._rightHand
      _head = source._head
      _trackingProtocolVersion = source._trackingProtocolVersion
      _sampleTime = source._sampleTime
      _headTime = source._headTime
      _leftTime = source._leftTime
      _rightTime = source._rightTime
      _headValid = source._headValid
      _leftValid = source._leftValid
      _rightValid = source._rightValid
      _predictionSeconds = source._predictionSeconds
      _diagnosticsVersion = source._diagnosticsVersion
      _headAnchorValid = source._headAnchorValid
      _videoRequired = source._videoRequired
      _videoReady = source._videoReady
      _videoReason = source._videoReason
      _headLossSeq = source._headLossSeq
      _leftLossSeq = source._leftLossSeq
      _rightLossSeq = source._rightLossSeq
      _lastWriteMs = source._lastWriteMs
      _packetsSent = source._packetsSent
      _headLossReason = source._headLossReason
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._leftHand) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._rightHand) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._head) }()
        case 4: try { try decoder.decodeSingularUInt32Field(value: &_storage._trackingProtocolVersion) }()
        case 5: try { try decoder.decodeSingularDoubleField(value: &_storage._sampleTime) }()
        case 6: try { try decoder.decodeSingularDoubleField(value: &_storage._headTime) }()
        case 7: try { try decoder.decodeSingularDoubleField(value: &_storage._leftTime) }()
        case 8: try { try decoder.decodeSingularDoubleField(value: &_storage._rightTime) }()
        case 9: try { try decoder.decodeSingularBoolField(value: &_storage._headValid) }()
        case 10: try { try decoder.decodeSingularBoolField(value: &_storage._leftValid) }()
        case 11: try { try decoder.decodeSingularBoolField(value: &_storage._rightValid) }()
        case 12: try { try decoder.decodeSingularDoubleField(value: &_storage._predictionSeconds) }()
        case 13: try { try decoder.decodeSingularUInt32Field(value: &_storage._diagnosticsVersion) }()
        case 14: try { try decoder.decodeSingularBoolField(value: &_storage._headAnchorValid) }()
        case 15: try { try decoder.decodeSingularBoolField(value: &_storage._videoRequired) }()
        case 16: try { try decoder.decodeSingularBoolField(value: &_storage._videoReady) }()
        case 17: try { try decoder.decodeSingularStringField(value: &_storage._videoReason) }()
        case 18: try { try decoder.decodeSingularUInt64Field(value: &_storage._headLossSeq) }()
        case 19: try { try decoder.decodeSingularUInt64Field(value: &_storage._leftLossSeq) }()
        case 20: try { try decoder.decodeSingularUInt64Field(value: &_storage._rightLossSeq) }()
        case 21: try { try decoder.decodeSingularDoubleField(value: &_storage._lastWriteMs) }()
        case 22: try { try decoder.decodeSingularUInt64Field(value: &_storage._packetsSent) }()
        case 23: try { try decoder.decodeSingularStringField(value: &_storage._headLossReason) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._leftHand {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._rightHand {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._head {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      if _storage._trackingProtocolVersion != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._trackingProtocolVersion, fieldNumber: 4)
      }
      if _storage._sampleTime.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._sampleTime, fieldNumber: 5)
      }
      if _storage._headTime.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._headTime, fieldNumber: 6)
      }
      if _storage._leftTime.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._leftTime, fieldNumber: 7)
      }
      if _storage._rightTime.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._rightTime, fieldNumber: 8)
      }
      if _storage._headValid != false {
        try visitor.visitSingularBoolField(value: _storage._headValid, fieldNumber: 9)
      }
      if _storage._leftValid != false {
        try visitor.visitSingularBoolField(value: _storage._leftValid, fieldNumber: 10)
      }
      if _storage._rightValid != false {
        try visitor.visitSingularBoolField(value: _storage._rightValid, fieldNumber: 11)
      }
      if _storage._predictionSeconds.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._predictionSeconds, fieldNumber: 12)
      }
      if _storage._diagnosticsVersion != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._diagnosticsVersion, fieldNumber: 13)
      }
      if _storage._headAnchorValid != false {
        try visitor.visitSingularBoolField(value: _storage._headAnchorValid, fieldNumber: 14)
      }
      if _storage._videoRequired != false {
        try visitor.visitSingularBoolField(value: _storage._videoRequired, fieldNumber: 15)
      }
      if _storage._videoReady != false {
        try visitor.visitSingularBoolField(value: _storage._videoReady, fieldNumber: 16)
      }
      if !_storage._videoReason.isEmpty {
        try visitor.visitSingularStringField(value: _storage._videoReason, fieldNumber: 17)
      }
      if _storage._headLossSeq != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._headLossSeq, fieldNumber: 18)
      }
      if _storage._leftLossSeq != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._leftLossSeq, fieldNumber: 19)
      }
      if _storage._rightLossSeq != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._rightLossSeq, fieldNumber: 20)
      }
      if _storage._lastWriteMs.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._lastWriteMs, fieldNumber: 21)
      }
      if _storage._packetsSent != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._packetsSent, fieldNumber: 22)
      }
      if !_storage._headLossReason.isEmpty {
        try visitor.visitSingularStringField(value: _storage._headLossReason, fieldNumber: 23)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_HandUpdate, rhs: Handtracking_HandUpdate) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._leftHand != rhs_storage._leftHand {return false}
        if _storage._rightHand != rhs_storage._rightHand {return false}
        if _storage._head != rhs_storage._head {return false}
        if _storage._trackingProtocolVersion != rhs_storage._trackingProtocolVersion {return false}
        if _storage._sampleTime != rhs_storage._sampleTime {return false}
        if _storage._headTime != rhs_storage._headTime {return false}
        if _storage._leftTime != rhs_storage._leftTime {return false}
        if _storage._rightTime != rhs_storage._rightTime {return false}
        if _storage._headValid != rhs_storage._headValid {return false}
        if _storage._leftValid != rhs_storage._leftValid {return false}
        if _storage._rightValid != rhs_storage._rightValid {return false}
        if _storage._predictionSeconds != rhs_storage._predictionSeconds {return false}
        if _storage._diagnosticsVersion != rhs_storage._diagnosticsVersion {return false}
        if _storage._headAnchorValid != rhs_storage._headAnchorValid {return false}
        if _storage._videoRequired != rhs_storage._videoRequired {return false}
        if _storage._videoReady != rhs_storage._videoReady {return false}
        if _storage._videoReason != rhs_storage._videoReason {return false}
        if _storage._headLossSeq != rhs_storage._headLossSeq {return false}
        if _storage._leftLossSeq != rhs_storage._leftLossSeq {return false}
        if _storage._rightLossSeq != rhs_storage._rightLossSeq {return false}
        if _storage._lastWriteMs != rhs_storage._lastWriteMs {return false}
        if _storage._packetsSent != rhs_storage._packetsSent {return false}
        if _storage._headLossReason != rhs_storage._headLossReason {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Handtracking_HandUpdateAck: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HandUpdateAck"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}message\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.message) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Handtracking_HandUpdateAck, rhs: Handtracking_HandUpdateAck) -> Bool {
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
